name: CI/CD Pipeline

on:
  push:
    branches: [main]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the code from your GitHub repository

      - name: Deploy to Vercel
        run: |
          npx vercel --prod  # Deploy to Vercel production
        env:
          VERCEL_TOKEN: ${{Vercel_Token}}  # Your Vercel token for authentication
          VERCEL_ORG_ID: ${{Vercel_user_id}}  # Optional, Vercel organization ID
          VERCEL_PROJECT_ID: ${{Vercel_Project_id}}  # Optional, Vercel project ID
    
